---
- hosts: localhost
  become: yes
  become_user: root
  tasks:
  - name: Git Clone
    git:
      repo: 'https://github.com/bhuvaneshwariarmugam/AnsibleRepo.git'
      dest: /root/bworkspace
      force: yes
  - name: Copy file to DocumentRoot
    copy: src=/root/bworkspace/ dest=/var/www/html
  - name: restart apache
    service: name=httpd state=restarted
